# Generated by Django 4.2 on 2026-01-06 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=1)),
                ('round1_completed', models.BooleanField(default=False)),
                ('round2_completed', models.BooleanField(default=False)),
                ('round1_time_taken', models.IntegerField(default=0)),
                ('round2_time_taken', models.IntegerField(default=0)),
                ('total_time_taken', models.IntegerField(default=0)),
                ('can_access_round2', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score', 'total_time_taken'],
            },
        ),
    ]
