# Generated by Django 4.2 on 2026-01-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round1_duration', models.IntegerField(default=1800, help_text='Duration in seconds (default: 30 mins)')),
                ('round1_total_questions', models.IntegerField(default=30)),
                ('round2_duration', models.IntegerField(default=2400, help_text='Duration in seconds (default: 40 mins)')),
                ('round2_total_questions', models.IntegerField(default=40)),
                ('top_n_participants', models.IntegerField(default=10, help_text='Number of participants to promote to Round 2')),
                ('contest_active', models.BooleanField(default=True)),
                ('round1_active', models.BooleanField(default=True)),
                ('round2_active', models.BooleanField(default=False)),
                ('score_per_question', models.IntegerField(default=4, help_text='Points awarded per correct answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contest Settings',
                'verbose_name_plural': 'Contest Settings',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(choices=[(1, 'Round 1'), (2, 'Round 2')], default=1)),
                ('category', models.CharField(choices=[('quantitative', 'Quantitative'), ('logical', 'Logical Reasoning'), ('verbal', 'Verbal Reasoning')], max_length=20)),
                ('question_text', models.TextField(help_text='The question to be asked')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('points', models.IntegerField(default=4, help_text='Points for this question')),
                ('order', models.IntegerField(default=0, help_text='Display order in quiz')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['round_number', 'order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('selected_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(default=0, help_text='Time in seconds to answer this question')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.question')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('participant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(default=0, help_text='Total time in seconds')),
                ('total_score', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='contest.participant')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
                'unique_together': {('participant', 'round_number')},
            },
        ),
    ]
