# Generated by Django 6.0.3 on 2026-03-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contestsettings_question_submission_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=100)),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['week', 'order_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(blank=True, help_text='Optional dynamic round mapping for weekly flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='contest.round'),
        ),
        migrations.AddField(
            model_name='submission',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contest.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='contest.week'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('week', 'order_number'), ('week', 'round_name')},
        ),
    ]
