# Generated by Django 6.0.3 on 2026-03-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_round_week_submission_score_question_round_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['week', 'order_number', 'id'], 'verbose_name': 'Round', 'verbose_name_plural': 'Rounds (all weeks)'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-start_date'], 'verbose_name': 'Week', 'verbose_name_plural': 'Weeks (schedule)'},
        ),
    ]
