# Generated by Django 6.0.3 on 2026-03-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_round_options_alter_week_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestsettings',
            options={'verbose_name': 'Contest settings (optional globals)', 'verbose_name_plural': 'Contest settings (optional globals)'},
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='schedule_round',
            field=models.ForeignKey(blank=True, help_text='Which schedule round (week + order) this attempt belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='contest.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=1800, help_text='Quiz timer for this round (seconds). Default 1800 = 30 minutes.'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_round__isnull', False)), fields=('participant', 'schedule_round'), name='unique_participant_schedule_round_attempt'),
        ),
    ]
