# Generated by Django 6.0.3 on 2026-03-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_alter_contestsettings_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestSettings',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['round__week', 'round__order_number', 'order', 'category'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='round',
            name='total_questions',
            field=models.PositiveIntegerField(default=30, help_text='Max number of questions to show in this round (picks first N by order).'),
        ),
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.ForeignKey(blank=True, help_text='Which schedule round (and thus which week) this question belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contest.round'),
        ),
        migrations.AlterField(
            model_name='question',
            name='round_number',
            field=models.PositiveIntegerField(default=1, help_text='Legacy mirror of round order; prefer setting Round below.'),
        ),
    ]
