# Generated by Django 6.0.3 on 2026-03-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_delete_contestsettings_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='promotion_cutoff_score',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum total score on this round to qualify for promotion to the next round (admin action / button). Leave empty to disable cutoff-based promotion.', null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='promotion_top_n',
            field=models.PositiveIntegerField(blank=True, help_text="For 'promote top N' tools: how many top scorers to move to the next round. Defaults to 50 if unset.", null=True),
        ),
    ]
