# Generated by Django 6.0.3 on 2026-03-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_remove_round_promotion_top_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='can_access_round2',
            field=models.BooleanField(default=False, help_text='Legacy: old gate for round 2; weekly flow uses QuizAttempt + Round.'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='current_round',
            field=models.IntegerField(default=1, help_text='Last / furthest round order (display hint). Real progress: Quiz attempts.'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='round1_completed',
            field=models.BooleanField(default=False, help_text='Legacy: set when schedule round order 1 is completed.'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='round2_completed',
            field=models.BooleanField(default=False, help_text='Legacy: set when schedule round order 2 is completed.'),
        ),
        migrations.AlterField(
            model_name='round',
            name='promotion_cutoff_score',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum total score on this round to qualify for the next round. Admin uses this for promotion (list action + button). Leave empty to disable.', null=True),
        ),
    ]
